### organization

GET https://claude.ai/api/organizations
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Accept-Language: en-US,en;q=0.5
Referer: https://claude.ai/chats
Content-Type: application/json
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Cookie: intercom-device-id-lupk8zyo=a5d0e526-db56-40a7-bed1-4d85d0a62bf0; __ssid=22a710ef562d36e3e161749f60d9cf4; __stripe_mid=f2126c8c-d5de-4e52-9fa1-94106428d4ad9834ec; sessionKey=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; activitySessionId=40a2dde9-cf39-4980-a36e-dfc5dcde06a3; __cf_bm=tVzuE0_ykdxg_GSwrRO5jQDejxao2dsdjDclCo.wFHs-1700185665-0-ARmSSAFy1VVZxJ0tdAyLEPLpfu2AfL81SVNT7IWWnv5k0nw5FMUWa/DW27B3SaDAOCONAitO1PZ1ilvd+Q5n8Qw=; cf_clearance=YrQe29PRsmtN7TG1UNdwFLcArFRMP6bWSbmGH_16Lls-1700185666-0-1-787701d4.f32104f3.2f765e34-0.2.1700185666; __stripe_sid=f6f0eb24-4d10-4dfb-9daf-f27a1289e149ed1241; intercom-session-lupk8zyo=UzdrTWVIVVlic1U2djR0T0o2NnBkTEttTG82WFZKMjhCajlCUkxDUDliWmdMMEU4QXRCTlV5Qy9SYWd4N05GZS0tb2l0eVpiSVFENUQ0L0o4TU16Y1VBQT09--0581b7960519cc66c94bb50eb054f222aa62ab0b
