### organization

GET https://claude.ai/api/organizations
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Accept-Language: en-US,en;q=0.5
Referer: https://claude.ai/chats
Content-Type: application/json
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Cookie: {{cookie}}

###
POST https://claude.ai/api/organizations/{{organizationId}}/chat_conversations
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Accept-Language: en-US,en;q=0.5
Referer: https://claude.ai/chats
Content-Type: application/json
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Cookie: {{cookie}}

{
  "uuid": "bd8d8d93-a0db-4ef9-a26d-03adfb53ddb3",
  "name": ""
}

### Get all conversations

GET http://localhost:8001/conversations

### Create new conversation

POST http://localhost:8001/conversations

###

POST http://localhost:8001/conversation/5010ba66-664a-4fbe-a448-f56f2d1eef9a
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Accept: text/event-stream
Accept-Language: en-US,en;q=0.5
Referer: https://claude.ai/chats
Content-Type: text/plain
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Cookie: {{cookie}}

What's your name?

###

DELETE http://localhost:8001/conversation/bd8d8d93-a0db-4ef9-a26d-03adfb53ddb3
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Accept-Language: en-US,en;q=0.5
Referer: https://claude.ai/chats
Content-Type: application/json
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Cookie: {{cookie}}

###

POST http://localhost:8001/generate-conversation-title/bd8d8d93-a0db-4ef9-a26d-03adfb53ddb1
Content-Type: text/plain
Cookie: {{cookie}}

你好！你叫什么名字？