#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Put this script into ./.git/hooks
# Put this script into ./.git/hooks
# Put this script into ./.git/hooks

echo "Running pre-commit building"
./gradlew clean
./gradlew build

if [ $? -ne 0 ]; then
    echo "Build must success before commit!"
    exit 1
fi