name: on-push-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Build fat jar
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew buildFatJar
          # build output path: ./build/libs/claude-api-server-all.jar

      - name: Release to github
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/libs/claude-api-server-all.jar"
          allowUpdates: true
          artifactErrorsFailBuild: true