name: on-push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Build
        env:
          CLAUDE_API_COOKIE: ${{ secrets.COOKIE }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean --parallel
          ./gradlew build --parallel
          ./gradlew :test --tests "com.pgleqi.ApplicationTest" --tests "com.pgleqi.UnitTest" --parallel
